[project]
name = "chaplifx2"
version = "1.0.2"
description = "A simple media app for shows and films"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash>=3.2.0",
    "dash-extensions>=1.0.20",
    "fastapi>=0.139.0",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.12.5",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.42",
    "uvicorn>=0.49.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.8",
    "pytest>=8.4.1",
    "testcontainers[postgres]>=4.14.2",
    "ty>=0.0.47",
]
